server:  
  port: ${PORT:8088}

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
          
ribbon:
  eureka:
    enabled: true

spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: flashcard
  datasource:
    platform: postgres
    schema: flashcard
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: bondstone
    driverClassName: org.postgresql.Driver
    